// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskProject.DataAccessLayer.Concreate;

#nullable disable

namespace TaskProject.DataAccessLayer.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    [Migration("20240710144857_migThird")]
    partial class migThird
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskProject.EntityLayer.Concreate.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Toys"
                        });
                });

            modelBuilder.Entity("TaskProject.EntityLayer.Concreate.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "High performance laptop",
                            ImageUrl = "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/lowres/c08478684.png",
                            Name = "Laptop",
                            Price = 1500.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "10 inch tablet",
                            ImageUrl = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/lenovo/thumb/untitled-1-3_large.jpg",
                            Name = "Tablet",
                            Price = 400.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Interesting book",
                            ImageUrl = "https://www.panelkirtasiye.com/productimages/468746/big/9786258431254_1.jpg",
                            Name = "Book 1",
                            Price = 20.00m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Description = "Remote-controlled toy car",
                            ImageUrl = "https://cdn.civilim.com/productimages/353321/big/86992623400652.jpg",
                            Name = "Toy Car",
                            Price = 45.00m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "Light and stylish summer dress",
                            ImageUrl = "https://i.ebayimg.com/images/g/OoIAAOSwqMtdmUEp/s-l1600.jpg",
                            Name = "Summer Dress",
                            Price = 85.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "4K monitor",
                            ImageUrl = "https://www.casper.com.tr/uploads/2023/09/casper-nirvana-238-monitor-03_op.webp",
                            Name = "Monitor",
                            Price = 350.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Interesting book",
                            ImageUrl = "https://img.kitapyurdu.com/v1/getImage/fn:5847593/wh:true/wi:800",
                            Name = "Book 2",
                            Price = 60.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Latest model smartphone",
                            ImageUrl = "https://cdn.cimri.io/image/1200x1200/apple-iphone-15-5g-128gb_865272811.jpg",
                            Name = "Smartphone",
                            Price = 999.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Noise cancelling headphones",
                            ImageUrl = "https://enteknoloji.com.tr/cdn/shop/files/air-3-bluetooth-kulaklik-1.1.png?v=1693815672&width=2048",
                            Name = "Headphones",
                            Price = 199.00m
                        });
                });

            modelBuilder.Entity("TaskProject.EntityLayer.Concreate.Product", b =>
                {
                    b.HasOne("TaskProject.EntityLayer.Concreate.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TaskProject.EntityLayer.Concreate.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
